server:
  port: 80
spring:
  application:
    name: zuul-local
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka